### ISSUE TITLE
boost::signals2::connection  use of deprecated header

### ISSUE THREAD

**Issue by dkruempe** [boostorg/signals2#48] opened 2020-11-15 19:55 UTC
Hi,
during the compile time of the current boost library 1.74 I get the following message.

In file included from /usr/local/include/boost/signals2.hpp:19:
In file included from /usr/local/include/boost/signals2/signal.hpp:22:
In file included from /usr/local/include/boost/signals2/connection.hpp:22:
In file included from /usr/local/include/boost/signals2/detail/null_output_iterator.hpp:14:
/usr/local/include/boost/function_output_iterator.hpp:14:1: warning: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead. [-W#pragma-messages]
BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")

**Comment by fmhess** [comment] 2020-11-15 21:22
Duplicate of #45

**Closed by fmhess** 2020-11-15 21:22 UTC
