### ISSUE TITLE
clang-tidy is reporting "Use of memory after it is freed"

### ISSUE THREAD

**Issue by hg-zt** [boostorg/signals2#59] opened 2022-04-02 12:23 UTC
Hi, do you think it is misreporting? If it is I would like to suppress the warning

```cpp
#include <boost/signals2.hpp>

int main()
{
  boost::signals2::signal<void ()> sig;
  sig.connect([]{});
  sig();
}
```

The output of `clang-tidy`

```bash
❯ clang-tidy-14 --checks='clang-diag*' ../a.cpp
1 warning generated.
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:22: warning: Use of memory after it is freed [clang-analyzer-cplusplus.NewDelete]
        if(pi_ != 0) pi_->weak_release();
                     ^
/tmp/foo/a.cpp:10:3: note: Calling 'signal::connect'
  sig.connect([]{});
  ^~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:691:16: note: Calling 'signal_impl::connect'
        return (*_pimpl).connect(slot, position);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:164:18: note: Calling 'signal_impl::nolock_connect'
          return nolock_connect(lock, slot, position);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:552:14: note: 'position' is equal to at_back
          if(position == at_back)
             ^~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:552:11: note: Taking true branch
          if(position == at_back)
          ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:562:29: note: Calling implicit destructor for 'weak_ptr<boost::signals2::detail::connection_body_base>'
          return connection(newConnectionBody);
                            ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:562:29: note: Calling '~weak_count'
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:12: note: Field 'pi_' is not equal to null
        if(pi_ != 0) pi_->weak_release();
           ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:9: note: Taking true branch
        if(pi_ != 0) pi_->weak_release();
        ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:22: note: Calling 'sp_counted_base::weak_release'
        if(pi_ != 0) pi_->weak_release();
                     ^~~~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:132:13: note: Assuming the condition is true
        if( atomic_decrement( &weak_count_ ) == 1 )
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:132:9: note: Taking true branch
        if( atomic_decrement( &weak_count_ ) == 1 )
        ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:134:13: note: Calling 'sp_counted_base::destroy'
            destroy();
            ^~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:99:9: note: Memory is released
        delete this;
        ^~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:134:13: note: Returning; memory was released
            destroy();
            ^~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:22: note: Returning; memory was released
        if(pi_ != 0) pi_->weak_release();
                     ^~~~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:562:29: note: Returning from '~weak_count'
          return connection(newConnectionBody);
                            ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:562:29: note: Returning from destructor for 'weak_ptr<boost::signals2::detail::connection_body_base>'
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:164:18: note: Returning; memory was released
          return nolock_connect(lock, slot, position);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/detail/signal_template.hpp:691:16: note: Returning; memory was released
        return (*_pimpl).connect(slot, position);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/foo/a.cpp:10:3: note: Returning; memory was released
  sig.connect([]{});
  ^~~~~~~~~~~~~~~~~
/tmp/foo/a.cpp:10:19: note: Calling '~connection'
  sig.connect([]{});
                  ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/connection.hpp:265:22: note: Calling implicit destructor for 'weak_ptr<boost::signals2::detail::connection_body_base>'
      ~connection() {}
                     ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/signals2/connection.hpp:265:22: note: Calling '~weak_count'
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:12: note: Field 'pi_' is not equal to null
        if(pi_ != 0) pi_->weak_release();
           ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:9: note: Taking true branch
        if(pi_ != 0) pi_->weak_release();
        ^
/home/hg/.conan/data/boost/1.78.0/_/_/package/cfef62e446e1bb07894de4523f2649afdfa94524/include/boost/smart_ptr/detail/shared_count.hpp:586:22: note: Use of memory after it is freed
        if(pi_ != 0) pi_->weak_release();
```

**Comment by fmhess** [comment] 2022-04-03 23:05
It looks like it is coming from boost::weak_ptr have you tried reproducing
this with just destroying a shared_ptr and then a weak_ptr that was
referencing it?

**Comment by hg-zt** [comment] 2022-04-06 06:47
No warning in both cases.
```cpp
#include <boost/smart_ptr/weak_ptr.hpp>

int main() {
  {
    auto s1 = boost::shared_ptr<int>{};
    boost::weak_ptr<int> w1{s1};
    s1.reset();
  }
  {
    auto *s2 = new boost::shared_ptr<int>{};
    boost::weak_ptr<int> w2{*s2};
    delete s2;
  }
}
```

And I found there is no warning before boost/1.74
w/o warning: 1.65, 1.73
w/ warning: 1.74, 1.76, 1.77, 1.78

**Comment by fmhess** [comment] 2022-04-06 17:12
What if the shared_ptr actually owns something before being assigned to the
weak_ptr?  In your cases it is empty.

**Comment by fmhess** [comment] 2022-04-10 16:54
I was able to reproduce the clang-tidy warning using your original example.  I think clang-tidy is just getting confused about when things actually get deleted.

**Comment by fmhess** [comment] 2022-04-14 18:03
For the record, valgrind doesn't detect any memory errors when running the program clang-tidy complained about.

**Closed by fmhess** 2022-04-14 18:03 UTC
